dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    packages:
    - doxygen
    - doxygen-doc
    - doxygen-latex
    - doxygen-gui
    - graphvis
script:
- doxygen Doxyfile
- cmake .
- cmake --build .
- cmake --build . --target test
- cmake --build . --target package
deploy:
  - provide: script
    skip_cleanup: true
    script:
      - curl -f -T metapro-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uhankhenshaw:$BINTRAY_API_KEY "https://api.bintray.com/content/hankhenshaw/MidRep/Sfinae/$TRAVIS_BUILD_NUMBER/metapro-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64;publish=1"
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    local_dir: $TRAVIS_BUILD_DIR/doxygen/html
    github_token: $GH_REPO_TOKEN
    on:
      branch: master